version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo "Installing awscli ..."
      - pip install --upgrade awscli
      - pip install boto3

  pre_build:
    commands:
      - echo "Invoke step functions"
      - aws lambda invoke --function-name invokeTrainingStepFunction --region us-east-1 out


